Repository ahsu1230/mathnavigatorSite, pull requests merged in 2020-07, with the labels that each got.

#158 Afh table
  constellations/orion/go.sum
  constellations/orion/src/controllers/ask_for_help_controller.go
  constellations/orion/src/controllers/ask_for_help_controller_test.go
  constellations/orion/src/controllers/testUtils/domains.go
  constellations/orion/src/controllers/testUtils/repos.go
  constellations/orion/src/domains/ask_for_help.go
  constellations/orion/src/domains/ask_for_help_valid_test.go
  constellations/orion/src/repos/ask_for_help_repo.go
  constellations/orion/src/repos/ask_for_help_repo_test.go
  constellations/orion/src/repos/init.go
  constellations/orion/src/repos/migrations/000024_create_table_ask_for_help.down.sql
  constellations/orion/src/repos/migrations/000024_create_table_ask_for_help.up.sql
  constellations/orion/src/router/handler.go
  constellations/orion/src/tests_integration/ask_for_help_integration_test.go
  constellations/orion/src/tests_integration/utils/database.go
Labels: peer-reviewed

#166 Responsive achievements page
  constellations/gemini-user/src/achievements/achievements.sass
Labels: final-review, peer-reviewed

#164 added announcement page on user site
  constellations/gemini-user/package.json
  constellations/gemini-user/src/announcements/announce.js
  constellations/gemini-user/src/announcements/announce.sass
  constellations/gemini-user/src/app/index.js
Labels: final-review

#165 responsive intern page
  constellations/gemini-user/src/internship/internship.js
  constellations/gemini-user/src/internship/internship.sass
Labels: final-review, peer-reviewed

#173 Achievements & semesters flexbox
  constellations/gemini-admin/src/achieve/achieve.sass
  constellations/gemini-admin/src/semester/semester.sass
Labels: final-review

#175 New branch for help page
  constellations/gemini-admin/src/header/header.js
  constellations/gemini-admin/src/help/help.js
  constellations/gemini-admin/src/help/help.sass
  constellations/gemini-admin/src/index.js
Labels: final-review

#169 Start data
  constellations/clients/orionFakeDataFiller/filler.go
Labels: final-review

#176 User search endpoint
  constellations/orion/src/controllers/account_controller_test.go
  constellations/orion/src/controllers/testUtils/repos.go
  constellations/orion/src/controllers/user_controller.go
  constellations/orion/src/controllers/user_controller_test.go
  constellations/orion/src/repos/migrations/000025_drop_table_users.down.sql
  constellations/orion/src/repos/migrations/000025_drop_table_users.up.sql
  constellations/orion/src/repos/migrations/000027_create_table_users.down.sql
  constellations/orion/src/repos/migrations/000027_create_table_users.up.sql
  constellations/orion/src/repos/user_repo.go
  constellations/orion/src/router/handler.go
  constellations/orion/src/tests_integration/user_integration_test.go
Labels: final-review, peer-reviewed

#168 Announcement popup
  constellations/gemini-user/src/home/__snapshots__/home.test.js.snap
  constellations/gemini-user/src/home/home.js
  constellations/gemini-user/src/home/homeAnnounce.js
  constellations/gemini-user/src/home/homeAnnounce.sass
  constellations/gemini-user/src/utils/storage.js
Labels: final-review, peer-reviewed

#154 Adding price_lump
  constellations/orion/src/domains/class.go
  constellations/orion/src/domains/class_valid_test.go
  constellations/orion/src/repos/class_repo.go
  constellations/orion/src/repos/class_repo_test.go
  constellations/orion/src/repos/migrations/000022_add_price_lump_at_classes.down.sql
  constellations/orion/src/repos/migrations/000022_add_price_lump_at_classes.up.sql
  constellations/orion/src/tests_integration/class_integration_test.go
Labels: peer-reviewed

#171 Added text input component
  constellations/gemini-admin/assets/checkmark_green.svg
  constellations/gemini-admin/assets/checkmark_light_blue.svg
  constellations/gemini-admin/package.json
  constellations/gemini-admin/src/_.constants.sass
  constellations/gemini-admin/src/programs/program.js
  constellations/gemini-admin/src/programs/program.sass
  constellations/gemini-admin/src/programs/program.styl
  constellations/gemini-admin/src/programs/programEdit.js
  constellations/gemini-admin/src/programs/programEdit.sass
  constellations/gemini-admin/src/programs/programEdit.styl
  constellations/gemini-admin/src/programs/programRow.js
  constellations/gemini-admin/src/programs/programRow.sass
  constellations/gemini-admin/src/programs/programRow.styl
  constellations/gemini-admin/src/utils/inputText.js
  constellations/gemini-admin/src/utils/inputText.sass
  constellations/gemini-admin/webpack.common.js
Labels: final-review, peer-reviewed

#157 Adding payment_notes
  constellations/orion/src/domains/class.go
  constellations/orion/src/repos/class_repo.go
  constellations/orion/src/repos/class_repo_test.go
  constellations/orion/src/repos/migrations/000023_add_payment_notes_at_classes.down.sql
  constellations/orion/src/repos/migrations/000023_add_payment_notes_at_classes.up.sql
  constellations/orion/src/tests_integration/class_integration_test.go
Labels: final-review, peer-reviewed

#178 fix the issue of help.sass affecting other pages
  constellations/gemini-admin/src/help/help.js
  constellations/gemini-admin/src/help/help.sass
Labels: final-review, peer-reviewed

#181 added dropdown for the full state of a class
  constellations/gemini-admin/src/classes/classEdit.js
  constellations/gemini-admin/src/classes/classEdit.sass
Labels: final-review, peer-reviewed

#183 home dashboard
  constellations/gemini-admin/src/home/home.js
  constellations/gemini-admin/src/home/home.sass
  constellations/gemini-admin/src/home/home.styl
Labels: final-review, peer-reviewed

#177 User afh
  constellations/orion/src/controllers/controllers_util.go
  constellations/orion/src/controllers/testUtils/domains.go
  constellations/orion/src/controllers/testUtils/repos.go
  constellations/orion/src/controllers/user_afh_controller.go
  constellations/orion/src/controllers/user_afh_controller_test.go
  constellations/orion/src/domains/user_afh.go
  constellations/orion/src/repos/init.go
  constellations/orion/src/repos/migrations/000026_create_table_users.down.sql
  constellations/orion/src/repos/migrations/000026_create_table_users.up.sql
  constellations/orion/src/repos/migrations/000027_create_table_user_afh.down.sql
  constellations/orion/src/repos/migrations/000027_create_table_user_afh.up.sql
  constellations/orion/src/repos/user_afh_repo.go
  constellations/orion/src/repos/user_afh_repo_test.go
  constellations/orion/src/router/handler.go
  constellations/orion/src/tests_integration/user_afh_integration_test.go
  constellations/orion/src/tests_integration/utils/database.go
Labels: final-review, peer-reviewed

#180 Admin AFH pages
  constellations/gemini-admin/src/ask_for_help/afh.js
  constellations/gemini-admin/src/ask_for_help/afh.sass
  constellations/gemini-admin/src/ask_for_help/afhEdit.js
  constellations/gemini-admin/src/ask_for_help/afhEdit.sass
  constellations/gemini-admin/src/ask_for_help/afhEditDateTime.js
  constellations/gemini-admin/src/ask_for_help/afhEditDateTime.sass
  constellations/gemini-admin/src/header/header.js
  constellations/gemini-admin/src/index.js
Labels: final-review

#189 Added user afh and class functionality
  constellations/gemini-admin/src/user/userAFH.js
  constellations/gemini-admin/src/user/userAFH.sass
  constellations/gemini-admin/src/user/userClass.js
  constellations/gemini-admin/src/user/userClass.sass
Labels: peer-reviewed

#185 Transaction table
  constellations/orion/src/controllers/testUtils/domains.go
  constellations/orion/src/controllers/testUtils/repos.go
  constellations/orion/src/controllers/transaction_controller.go
  constellations/orion/src/controllers/transaction_controller_test.go
  constellations/orion/src/domains/transaction.go
  constellations/orion/src/domains/transaction_valid_test.go
  constellations/orion/src/repos/init.go
  constellations/orion/src/repos/migrations/000029_create_table_transactions.down.sql
  constellations/orion/src/repos/migrations/000029_create_table_transactions.up.sql
  constellations/orion/src/repos/transaction_repo.go
  constellations/orion/src/repos/transaction_repo_test.go
  constellations/orion/src/router/handler.go
  constellations/orion/src/tests_integration/transactions_integration_test.go
  constellations/orion/src/tests_integration/utils/database.go
Labels: final-review, peer-reviewed

#191 More input fields for admin class page
  constellations/gemini-admin/src/classes/classEdit.js
Labels: final-review, peer-reviewed

#192 Final userclasses table PR
  constellations/orion/src/controllers/testUtils/domains.go
  constellations/orion/src/controllers/testUtils/repos.go
  constellations/orion/src/controllers/user_class_controller.go
  constellations/orion/src/controllers/user_class_controller_test.go
  constellations/orion/src/domains/user_afh.go
  constellations/orion/src/domains/user_class.go
  constellations/orion/src/repos/init.go
  constellations/orion/src/repos/migrations/000028_create_table_userclass.down.sql
  constellations/orion/src/repos/migrations/000028_create_table_userclass.up.sql
  constellations/orion/src/repos/user_class_repo.go
  constellations/orion/src/repos/user_class_repo_test.go
  constellations/orion/src/router/handler.go
  constellations/orion/src/tests_integration/user_afh_integration_test.go
  constellations/orion/src/tests_integration/user_class_integration_test.go
  constellations/orion/src/tests_integration/utils/database.go
Labels: final-review

#199 Added documentation
  constellations/gemini-admin/src/utils/inputText.js
Labels: final-review, peer-reviewed

#200 Switched to sass
  constellations/gemini-admin/package.json
  constellations/gemini-admin/src/app.sass
  constellations/gemini-admin/src/app.styl
  constellations/gemini-admin/src/header/header.js
  constellations/gemini-admin/src/header/header.sass
  constellations/gemini-admin/src/header/header.styl
  constellations/gemini-admin/src/index.js
  constellations/gemini-admin/src/modals/modal.js
  constellations/gemini-admin/src/modals/modal.sass
  constellations/gemini-admin/src/modals/modal.styl
  constellations/gemini-admin/src/modals/okayModal.js
  constellations/gemini-admin/src/modals/okayModal.sass
  constellations/gemini-admin/src/modals/okayModal.styl
  constellations/gemini-admin/src/modals/yesnoModal.js
  constellations/gemini-admin/src/modals/yesnoModal.sass
  constellations/gemini-admin/src/modals/yesnoModal.styl
  constellations/gemini-admin/src/static.styl
  constellations/gemini-admin/webpack.common.js
Labels: final-review, peer-reviewed
